<?php

/**
 * Transforms a textfield into a US formatted phone number.
 */

/**
* Converts phone numbers to the US based formatting standard
*/
function formatPhone($num) {
  $num = preg_replace('/[^0-9]/', '', $num);
  $len = strlen($num);
  if($len == 7) {
    $num = preg_replace('/([0-9]{3})([0-9]{4})/', '$1-$2', $num); 
    }
  elseif($len == 10) {
    $num = preg_replace('/([0-9]{3})([0-9]{3})([0-9]{4})/', '($1) $2-$3', $num);
  }
 
return $num;
}
 
// echo formatPhone('1 208 - 386 2934');
// will print: (208) 386-2934 </code>


/**
 * Implements hook_field_formatter_info().
 */
function phoneus_field_formatter_info() {
  return array(
    'phoneus_example_field' => array(
      'label' => t('US Phone Number'),
      'field types' => array('text'),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 */
function phoneus_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {
  if ($items) {
  switch ($display['type']) {
    case 'phoneus_example_field':
      $element[0]['#type'] = 'markup';
      $element[0]['#markup'] = theme('phoneus_example_field', array('value' => $items[0]['safe_value']));
      break;
  }
  }

  return $element;
}


/**
 * Theme the example field.
 */
function theme_phoneus_example_field($variables) {
$variables['value'] = formatPhone($variables['value']);
  return $variables['value'];

}


/**
 * Implements hook_theme().
 */
function phoneus_theme() {
  return array(
    'phoneus_example_field' => array(
      'variables' => array('value' => NULL),
    ),
  );
}